CREATE TABLE "CBW"."EMPLOYEE_158" (
    "ID"            NUMBER,
    "NAME"          VARCHAR2(225),
    "ORGANIZATION"  VARCHAR2(225),
    "TYPE"          VARCHAR2(225),
    "ACTIVE"        VARCHAR2(225),
    "DESCRIPTION"   VARCHAR2(225),
    CONSTRAINT "EMPLOYEE_158_PK" PRIMARY KEY("ID")
);

select * from EMPLOYEE_158;